version: '3.7'

services:
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./app:/symfony
    restart: always
    ports:
      - "9999:80"

  php-fpm:
    build:
      context: ./docker/php-fpm
    volumes:
      - ./app:/symfony

  php-cli:
    build:
      context: ./docker/php-cli
    tty: true
    volumes:
      - ./app:/symfony